using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MSB_Virus_Scanner
{
    public static class Whitelist
    {
        public static string[] files =
        {
            @"VC_redist.x64.exe",
            @"VC_redist.x86.exe",
            @"vcredist_x64.exe",
            @"vcredist_x86.exe",
            @"ArcGIS_Desktop_1051_156235(1).exe",
            @"ArcGIS-1051-DT-NNQ2-PatchB\DT1051_P000029B_CleanUp.exe",
            @"ArcGISDesktop10_5_1Install\Desktop\instmsi3.exe",
            @"ArcGISDesktop10_5_1Install\Desktop\Setup.exe",
            @"ArcGISDesktop10_5_1Install\Patches\FlexCVE_x86\Setup.exe",
            @"DropboxUninstaller.exe",
            @"QtWebEngineProcess.exe", // dropbox related
            @"dbxsvc.exe",
            @"DismHost.exe",
            @"Dropbox.exe",
            @"airappinstaller.exe",
            @"WerFault.exe",
            @"Uninstall.exe",
            @"x86_Microsoft.VC80.CRTP_8.0.50727.762.exe",
            @"WinSSInstiX500WW2.exe",
            @"ose00000.exe",
            @"ose00001.exe",
            @"{219BB43A-8E43-4DE8-A10E-7BFDDBAABB6D}\Disk1\setup.exe",
            @"venv\Lib\site-packages\pip\_vendor\distlib\t32.exe",
            @"venv\Lib\site-packages\pip\_vendor\distlib\t64.exe",
            @"venv\Lib\site-packages\pip\_vendor\distlib\w32.exe",
            @"venv\Lib\site-packages\pip\_vendor\distlib\w64.exe",
            @"venv\Lib\site-packages\setuptools\cli.exe",
            @"venv\Lib\site-packages\setuptools\cli-32.exe",
            @"venv\Lib\site-packages\setuptools\cli-64.exe",
            @"venv\Lib\site-packages\setuptools\gui.exe",
            @"venv\Lib\site-packages\setuptools\gui-32.exe",
            @"venv\Lib\site-packages\setuptools\gui-64.exe",
            @"venv\Scripts\easy_install.exe",
            @"venv\Scripts\easy_install-2.7.exe",
            @"venv\Scripts\pip.exe",
            @"venv\Scripts\pip2.7.exe",
            @"venv\Scripts\pip2.exe",
            @"venv\Scripts\python.exe",
            @"venv\Scripts\pythonw.exe",
            @"venv\Scripts\wheel.exe",
            @"venv\Lib\site-packages\pip\_vendor\distlib\t32.exe",
            @"venv\Lib\site-packages\pip\_vendor\distlib\t64.exe",
            @"venv\Lib\site-packages\pip\_vendor\distlib\w32.exe",
            @"venv\Lib\site-packages\pip\_vendor\distlib\w64.exe",
            @"venv\Lib\site-packages\setuptools\cli-32.exe",
            @"venv\Lib\site-packages\setuptools\cli-64.exe",
            @"SQLMultiScript_1.4.2.1119.exe",
            @"McAfee\Agent\Current\MFEDATRU1200\Install\0000\Setup.exe",
            @"McAfee\Agent\data\McAfeeP2P\Current\MFEDATRU1200\Install\0000\743F251B2254BFF364850E7A7B65F2E1A726C9AD_Setup.exe",
            @"McAfee\Agent\data\McAfeeP2P\Current\TIER3APP0085\Install\0000\51A6A98FCC527DA7D7A0C643B6A3C305BA3FE671_Setup--VSE--Validation.Trust--Reset.exe",
            @"McAfee\Agent\data\McAfeeP2P\Current\VIRUSCAN8800\Install\0000\5B7D6EC66CF51F11F9BE6E1BDDB69F1A11B4775E_setupvse.exe",
            @"McAfee\Agent\data\McAfeeP2P\Current\VIRUSCAN8800\Install\0000\6CD68F8278D4C672BD0A1A9A12698CE190880B66_Uninst.exe",
            @"McAfee\Agent\data\McAfeeP2P\Current\VIRUSCAN8800\Install\0000\7C15504F811F8372607C6624891B8CFEF05E1499_Uninstx64.exe",
            @"McAfee\Agent\data\McAfeeP2P\Current\VIRUSCAN8800\Patch\11\0000\9EA7B60CE125EEB7DF0DDE46146DFD346C2C7B97_setup.exe",
            @"Package Cache\{06b884b0-4947-4439-859f-098e431012d6}\dotnet-sdk-2.1.202-win-x64.exe",
            @"Package Cache\{5807fad3-2c87-4429-9121-ab1b2eeeb928}\ZOLL Data Retriever Setup.exe",
            @"PFU\ScanSnap\SSDriver\S300\log\SSLogPD.exe",
            @"Quest\KACE\dell\InvColPC_8.0.4.1.exe",
            @"Quest\KACE\downloads\77354\Windows10Upgrade9252.exe",
            @"Quest\KACE\patches\Patch-Smart.AdobeShockwave12.3.1.201.exe",
            @"{513F5FDB-ADDB-4FA8-B5D9-9D0A8D0ED33B}\ARPPRODUCTICON.exe",
            @"{513F5FDB-ADDB-4FA8-B5D9-9D0A8D0ED33B}\ProHelpShrtct.748DF3F4_C6F4_48FA_AB08_A27F6C25AC0B.exe",
            @"{B5E1FB35-5E9D-4B40-ABA5-20F29A186889}\ARPPRODUCTICON.exe",
            @"{B5E1FB35-5E9D-4B40-ABA5-20F29A186889}\IPython_72555EF2C7EF4760BE5A6113FB326F90.exe",
            @"{B5E1FB35-5E9D-4B40-ABA5-20F29A186889}\Jupyter_4649E5FF9D70431D9AF03A96BFF78962.exe",
            @"{B5E1FB35-5E9D-4B40-ABA5-20F29A186889}\NewShortcut1.D0A70D39_352E_4EBA_98BC_1FBE63AFD8D4.exe",
            @"{B5E1FB35-5E9D-4B40-ABA5-20F29A186889}\ProOnlineHelp.D0A70D39_352E_4EBA_98BC_1FBE63AFD8D4.exe",
            @"{B5E1FB35-5E9D-4B40-ABA5-20F29A186889}\PyInteractive_D53CD3BB7B5944C78925CD4AF7FF7D10.exe",
            @"{B5E1FB35-5E9D-4B40-ABA5-20F29A186889}\PyPrompt_7153213105FB4FD982A73D5F2EF6A1CB.exe",
            @"advlimit.exe",
            @"ashelper.exe",
            @"atasanot.exe",
            @"atashost.exe",
            @"atasinst.exe",
            @"atauthor.exe",
            @"atscjoin.exe",
            @"AVLaunch.exe",
            @"cmdproxy.exe",
            @"id_uinit.exe",
            @"Identity.exe",
            @"instmsi3.exe",
            @"Launcher.exe",
            @"movemail.exe",
            @"nstvstub.exe",
            @"runemacs.exe",
            @"java-rmi.exe",
            @"ssvagent.exe",
            @"gpsbabel.exe",
            @"Egw-prod.exe",
            @"ScanSnap.exe",
            @"dotnetfx.exe",
            @"instmsiw.exe",
            @"scan2pdf.exe",
            @"bomgar",
            @"WebEx",
            @"AdobeARM.exe",
            @"SqlSupport_msi",
            @"sql_common_core_msi",
            @"GEARDIFx.exe",
            @"x86_Microsoft.VC80.CRTR_8.0.50727.762.exe",
            @"RealtekHDAudio",
            @"Dell\KACE",
            @"Dell\drivers",
            @"Quest\KACE",
            @"adksetup.exe",
            @"dwusplay.exe",
            @"audacity.exe",
            @"dwgviewr",
            @"Diploma6.exe",
            @"Opticom Firmware Package",
            @"ArcGIS",
            @"Autodesk",
            @"SetupISS.exe",
            @"igfxTray.exe",
            @"Anaconda2",
            @"Anaconda3",
            @"Miniconda3",
            @"fastboot.exe",
            @"SetupRST.exe",
            @"Roaming\Zoom",
            @"fastboot.exe",
            @"Dell Wireless Docking Software",
            @"VS2013.5.exe",
            @"VS2012.5.exe",
            @"Adobe\Shockwave 11\uninstaller.exe",
            @"Adobe\Shockwave 12\uninstaller.exe"
        };

        public static string[] profile_folders =
        {

            "3D Objects",
            "AppData",
            "Contacts",
            "Desktop",
            "Documents",
            "Downloads",
            "Dropbox",
            "Favorites",
            "Links",
            "Music",
            "OneDrive",
            "OpenVPN",
            "Pictures",
            "Saved Games",
            "Searchs",
            "Videos",
            "VirtualBox VMs"
        };

        public static string[] tasks =
        {
            "ActivityHelperEvery30",
            "AdobeAAMUpdater",
            "AdobeGCInvoker",
            "Adobe Acrobat Update Task",
            "Adobe Flash Player PPAPI Notifier",
            "Adobe Flash Player NPAPI Notifier",
            "Adobe Flash Player Updater",
            "Apple\\AppleSoftwareUpdate",
            "CCleaner",
            "ConvergeConnect",
            "Driver Support",
            "DropboxUpdateTaskMachineCore",
            "DropboxUpdateTaskMachineUA",
            "DropboxUpdateTaskUser",
            "Fujitsu Registration",
            "G2MUpdateTask",
            "G2MUploadTask",
            "GoogleUpdateTaskMachineCore",
            "GoogleUpdateTaskMachineUA",
            "GoogleUpdateTaskUser",
            "InstallDotNet452",
            "InstallMSBVirusSentry",
            "Intel\\Thunderbolt\\Start Thunderbolt",
            "Microsoft",
            @"OfficeSoftwareProtectionPlatform\SvcRestartTask",
            "OneDrive Standalone Update Task",
            "Opera scheduled Autoupdate",
            "RtHDVBg_PushButton",
            "UpdateMSBVirusSentry",
            "User_Feed_Synchronization",
            @"WPD\SqmUpload",
            "McAfee",
            "WWSync",
            "WWSYnc",
            "MindManager",
            "vagrant-vmware",
            "UpdateTask",
            "UpdaterEX",
            "Toolbox.exe",
            "Sync Toy",
            "SDMsgUpdate",
            "ROW Complaint Ticket Generator",
            "nWizard",
            "Logon_Trigger_WPS_Mon_Task",
            "LaunchSignup",
            "Launch Card Viewer",
            "ISM-UpdateService",
            "IUM-F1E24CA0",
            "Intel PTT EK Recertification",
            "HPLJCustParticipation",
            "GarminUpdaterTask",
            @"Games\UpdateCheck",
            "Dell SupportAssistAgent AutoUpdate",
            "CreateExplorerShellUnelevatedTask",
            "CouponViewer Toolbar",
            "ArcGIS Pro Indexing",
            "WasteWORKS",
            "Yahoo! Powered",
            "Validate Installation",
            "SystemHealer Run Delay",
            "StartDVR",
            "StartCN",
            "SlimCleaner Plus",
            "SidebarExecute",
            "Seagate_Install_Launch",
            "SaferBrowserProtectTask",
            "RealDownloader",
            "Postmaster",
            "PostMaster",
            "PCDEventLauncherTask",
            "Onsite_Watchdog",
            "One System Care Run Delay",
            "LaunchPreSignup",
            @"Intel\Intel Telemetry 2",
            "HPCustParticipation",
            "DBAgent",
            "Dell",
            "CUScheduled",
            "Check Updates",
            "Amazon Music Helper",
            "UpdateInfo",
            "IntelWiDi-Upgrade",
            "Optimize Start Menu Cache Files",
            "RunMSBVirusScanner",
            "ShadowCopyVolume",
            "InstallWindowsUpdateManagementService",
            "RefreshWindowsUpdateManagementService",
            "StartMSBUpdateService",
            "UpdateMSBService",
            "StartFabricTraces",
            "At1",
            "At2",
            "At3",
            "At4",
            "At5",
            "At6",
            "Clean Exchange Log Files",
            "Auto Rec N Post",
            "New World Notification Milestone Event",
            "copy alearoadsunique",
            "Farm Warmup",
            "Delete Old Windows Temp Files",
            "DeployWindowsUpdateManagementService",
            "GeocortexOptimizer",
            "Cartegraph",
            "Opt_Out",
            "PPC Address Update",
            @"{00C200B0-D178-4F6A-B2D8-54731AF518F1}",
            @"{0C0CBC32-9A75-4A7F-BEB3-8A2FFD90A8A3}",
            @"{10B0A507-6720-43E3-8C10-1A475590DD73}",
            @"{112F316F-B58A-4D69-A81A-0D222D856F9C}",
            @"{168769BB-8C27-48C9-A3FD-FEBBDAAEB73C}",
            @"{189ABC1D-4CDB-4ADC-AD9F-069A8345BADD}",
            @"{22FF8C69-97B3-4C86-9637-EDFBF8152342}",
            @"{286C9E25-440C-406C-A024-4D61A308BED6}",
            @"{31BD766A-3DBC-4AA1-8AE1-E383F01B7E4B}",
            @"{330BCFB3-9D5C-4E10-9DC5-5B4434E1A907}",
            @"{372F7FA6-EDAE-4804-ABA3-86B297C3426F}",
            @"{49CE555A-97C0-4364-8BCD-F3254D55010D}",
            @"{4A7FD591-8C3A-4572-883A-3BD9BC97374B}",
            @"{548CEC02-14DD-4B88-9053-D943E7E39ECD}",
            @"{57604982-FC46-4A24-BF99-4BC73E719C5D}",
            @"{5D427A90-8359-440B-8735-4E581A0FBDA7}",
            @"{5DA155C9-9E4F-4967-834E-5324D995CD93}",
            @"{5F541FBC-2975-4C5B-97B1-4D4BCFC12340}",
            @"{6D03036A-2380-4B6C-BA51-2FB11B29B5EC}",
            @"{6FD56334-B51B-4A1B-B5DB-23B0EA5FE0F7}",
            @"{7277A18D-AA4C-4019-AD3E-E93C74D11888}",
            @"{73888D36-32BF-408C-BD50-BA8FC697FD6B}",
            @"{74CAB39F-25F5-433D-91CD-08E57EE6B4B6}",
            @"{81A21133-3E27-4FFB-B9E7-A98F4BEE1445}",
            @"{87AFC258-C921-4BAF-B2F6-F2BF063BA7FB}",
            @"{88B59BAA-074B-4D9C-81AB-E2AF22E16087}",
            @"{8F113DD9-C135-4F98-875D-C656517AC2D1}",
            @"{A31288BD-E41C-46ED-ABF0-64ED920C6A6D}",
            @"{A5A9BF65-551D-4342-91F3-48125E4E0F36}",
            @"{A639A61D-0EE1-4849-AF2B-2D9B89E72938}",
            @"{A7E3DAB8-467A-468F-8ED5-5BB400024125}",
            @"{AD849F01-6A65-4A82-B34C-57227EED51F3}",
            @"{C5EE5A7B-EA7D-4349-8991-4EAB1809C450}",
            @"{D0F1A119-4295-4AEB-AB11-998AB48B178B}",
            @"{D721765B-1D1C-46B4-9E00-BC9433C0D7DC}",
            @"{D8705D40-428A-4FAC-B1B2-C889CC7D49E9}",
            @"{DBE86A5D-A977-41F6-BA1D-8E7C4E5F0447}",
            @"{E932B7B2-9D58-4487-8E9E-E0A4C6BE2A88}",
            @"{E93D8C56-1BEE-4142-8FC5-F6C42E2326CE}",
            @"{EBAACDE5-9C37-44FE-8CDF-E5E9CB8F95CC}",
            @"{EF59C6AF-912C-4602-B87B-2AF6DAC031FD}",
            @"{F12477ED-91D5-4745-AEA1-339A780A8D2B}",
            @"{F69560EC-7AE7-429D-B2D2-8C140EB502F7}",
            @"{FF9E12E3-97C5-4D6F-A6A2-2E14E132B755}",
            @"{08798207-4357-82B5-98B0-164321D596E3}",
            @"{14F6A078-A0BE-F942-4762-0081A4FACF63}",
            @"{19CC3A61-CC61-42DB-B782-4A58152F2B5F}",
            @"{21F0BAFC-89A4-471A-AA89-F24E060F2198}",
            @"{242B7E72-6DB8-4C07-83A2-AEE0D6EDDD26}",
            @"{27B6462B-A032-29E2-711A-7C1E5480806C}",
            @"{298E8A0A-DD6B-4944-9E27-ED7A45E541B0}",
            @"{2FB6EFAC-34E8-4A1A-B9A9-9694B9B95D33}",
            @"{3363BF00-D6E5-C798-8FEC-63A464851C7E}",
            @"{362FCE14-9F42-463D-8BD1-501F1DB7FB4D}",
            @"{3FE8264A-9170-496A-AF33-611E786865CB}",
            @"{45B681A9-F415-4675-A4A5-72FFF7B8F6E4}",
            @"{45E51FB1-1EC2-1B24-39BD-0BC32DDF9AEE}\Fefade",
            @"{4AD018ED-6051-4F5E-9687-EEF8101EFE2B}",
            @"{553FAB41-615C-4F31-BF6C-943BA5E15F50}",
            @"{64EEE8F9-5B5F-4003-86A1-827779D7EA4A}",
            @"{6771C54C-D609-4F37-A77D-48D300927B1B}",
            @"{6D742838-7FC4-4546-93A2-339D6CF483FF}",
            @"{72745AF0-1D94-40BE-A5C1-DA10FE5EC213}",
            @"{745E4B47-273A-45B1-A02F-12E4BF541406}",
            @"{74C9C1ED-BBD8-49FE-A569-A7316180F79A}",
            @"{789F158C-CF34-A227-160B-78AD72F9DC94}",
            @"{7A6ED855-2339-405F-ACF8-B339CDB9550B}",
            @"{7DE6A8EC-300F-5B46-5BC7-3F3F1023BB52}",
            @"{961805EF-BE4F-4BD0-9AAF-85290BD03B61}",
            @"{99A8FF5A-2D20-4413-9EE1-DFE523228693}",
            @"{9D86969D-089C-422C-B7B3-D77606D82790}",
            @"{9DD6227C-15F8-496D-BF30-A8430D1BA7BE}",
            @"{A1293BD8-BD3D-48BA-B28A-DAF6F06CC337}",
            @"{A47F9838-0699-4648-A1DD-94B58D2F18CD}",
            @"{A6DC0CB1-2D5D-4040-903D-A621220D102F}",
            @"{AF69D6CA-9FFE-449C-87A6-C8DF12B8F36A}",
            @"{BDEBB419-5266-492F-9CDB-A0444110FA72}",
            @"{C75CF709-7CE8-4218-AEAB-22312DC9DE95}",
            @"{CCFC3C9B-2621-4081-A504-82DE058EF60D}",
            @"{D6F49368-7F98-4351-BB32-4D7C23AE16FF}",
            @"{E032FEE5-7870-4EC6-A02C-D6E6FFCAC5FD}",
            @"{E2515D64-1199-4594-88CF-9E3D610F08CA}",
            @"{ED3AF8DA-8A6C-4409-8912-D967F3ED9A67}",
            @"{EDBD8C5C-FBA0-40BE-A414-1A4625AE5948}",
            @"{F25EF8DF-C3F2-4693-A253-B79AEBCC2335}",
            @"{FA1B5A45-CC60-41ED-A778-53BC37362658}",
        };

        public static string[] system32_folders =
        {
            @"0409",
            @"1033",
            @"AdvancedInstallers",
            @"af-ZA",
            @"am-et",
            @"AppLocker",
            @"appraiser",
            @"AppV",
            @"ar-SA",
            @"as-IN",
            @"az-Latn-AZ",
            @"be-BY",
            @"BestPractices",
            @"bg-BG",
            @"bn-BD",
            @"bn-IN",
            @"Boot",
            @"bs-Latn-BA",
            @"Bthprops",
            @"ca-ES",
            @"ca-ES-valencia",
            @"CatRoot",
            @"catroot2",
            @"chr-CHER-US",
            @"CodeIntegrity",
            @"com",
            @"config",
            @"Configuration",
            @"cs-CZ",
            @"cy-GB",
            @"da-DK",
            @"DDFs",
            @"de-DE",
            @"DiagSvcs",
            @"Dism",
            @"downlevel",
            @"drivers",
            @"DriverState",
            @"DriverStore",
            @"DRVSTORE",
            @"dsc",
            @"el-GR",
            @"en",
            @"en-GB",
            @"en-US",
            @"es-ES",
            @"es-MX",
            @"et-EE",
            @"eu-ES",
            @"F12",
            @"fa-IR",
            @"fi-FI",
            @"fil-PH",
            @"fr-CA",
            @"fr-FR",
            @"FxsTmp",
            @"ga-IE",
            @"gd-GB",
            @"gl-ES",
            @"GroupPolicy",
            @"GroupPolicyUsers",
            @"gu-IN",
            @"ha-Latn-NG",
            @"HardenedFabric",
            @"he-IL",
            @"hi-IN",
            @"hr-HR",
            @"hu-HU",
            @"hy-AM",
            @"hydrogen",
            @"ias",
            @"icsxml",
            @"id-ID",
            @"ig-NG",
            @"IME",
            @"inetsrv",
            @"InputMethod",
            @"Intel",
            @"ipam",
            @"Ipmi",
            @"is-IS",
            @"it-IT",
            @"ja-jp",
            @"ka-GE",
            @"kk-KZ",
            @"km-KH",
            @"kn-IN",
            @"kok-IN",
            @"ko-KR",
            @"ku-Arab-IQ",
            @"ky-KG",
            @"lb-LU",
            @"Licenses",
            @"LogFiles",
            @"lo-LA",
            @"lt-LT",
            @"lv-LV",
            @"lxss",
            @"Macromed",
            @"MailContactsCalendarSync",
            @"Microsoft",
            @"migration",
            @"migwiz",
            @"mi-NZ",
            @"mk-MK",
            @"ml-IN",
            @"mn-MN",
            @"mr-IN",
            @"MRT",
            @"MSDRM",
            @"MsDtc",
            @"ms-MY",
            @"mt-MT",
            @"MUI",
            @"my-mm",
            @"nb-NO",
            @"NDF",
            @"ne-NP",
            @"networklist",
            @"nl-NL",
            @"nn-NO",
            @"nso-ZA",
            @"Nui",
            @"oobe",
            @"OpenSSH",
            @"or-IN",
            @"pa-Arab-PK",
            @"pa-IN",
            @"pl-PL",
            @"PointOfService",
            @"Printing_Admin_Scripts",
            @"ProximityToast",
            @"prs-AF",
            @"pt-BR",
            @"pt-PT",
            @"quc-Latn-GT",
            @"quz-PE",
            @"ras",
            @"RasToast",
            @"Recovery",
            @"restore",
            @"ro-RO",
            @"RTCOM",
            @"ru-RU",
            @"rw-RW",
            @"sd-Arab-PK",
            @"SecureBootUpdates",
            @"ServerManagerInternal",
            @"setup",
            @"ShellExperiences",
            @"si-lk",
            @"sk-SK",
            @"SleepStudy",
            @"slmgr",
            @"sl-SI",
            @"SMI",
            @"Speech",
            @"Speech_OneCore",
            @"spool",
            @"spp",
            @"sppui",
            @"sq-AL",
            @"sr-Cyrl-BA",
            @"sr-Cyrl-RS",
            @"sr-Latn-RS",
            @"sru",
            @"sv-SE",
            @"sw-KE",
            @"Sysprep",
            @"SystemResetPlatform",
            @"ta-in",
            @"ta-lk",
            @"Tasks",
            @"Tasks_Migrated",
            @"te-IN",
            @"tg-Cyrl-TJ",
            @"th-TH",
            @"ti-ET",
            @"tk-TM",
            @"tn-ZA",
            @"tr-TR",
            @"tt-RU",
            @"ug-CN",
            @"uk-UA",
            @"UNP",
            @"ur-PK",
            @"uz-Latn-UZ",
            @"vi-VN",
            @"wbem",
            @"WCN",
            @"WDI",
            @"WinBioDatabase",
            @"WinBioPlugIns",
            @"WindowsPowerShell",
            @"winevt",
            @"WinMetadata",
            @"winrm",
            @"wo-SN",
            @"xh-ZA",
            @"yo-NG",
            @"zh-CN",
            @"zh-TW",
            @"zu-ZA",
            @"am-ET",
            @"catroot",
            @"InstallShield",
            @"ja-jp",
            @"Msdtc",
            @"sda",
            @"si-LK",
            @"sysprep",
            @"ta-IN",
        };

        public static string[] registry_run =
        {
            @"C:\ProgramData\bomgar-au",
            @"C:\Windows\System32\StikyNot.exe",
            @"Dropbox\Update\DropboxUpdate.exe",
            @"GoogleUpdateCore.exe",
            @"Microsoft\BingSvc\BingSvc.exe",
            @"chromium\application\chrome.exe",
            @"chromium\Application\chrome.exe",
            @"Amazon Music\Amazon Music",
            @"Skype\Phone\Skype.exe",
            @"Windows Sidebar\Sidebar.exe",
            @"Windows Sidebar\sidebar.exe",
            @"FaxFinder Client\faxfinderclient.exe",
            @"C8IS5\OptionalFeatures.exe",
            @"Office14\MSOSYNC.EXE",
            @"Tencent\WeChat\WeChat.exe",
            @"ShoreWare Client\ShoreTel.exe",
            @"Mitel\Connect\ShoreTel.exe",
            @"Microsoft Office\Office16\lync.exe",
            @"DYMO Label Software\DymoQuickPrint.exe",
            @"Acrobat\AdobeCollabSync.exe",
            @"C:\KACE\engine\kaceengine.exe",
            @"C:\KapishMonitor.exe",
            @"C:\Program Files (x86)\Airtame\airtame-application.exe",
            @"C:\Program Files (x86)\Common Files\Adobe\AdobeGCClient\AGCInvokerUtility.exe",
            @"C:\Program Files (x86)\Common Files\Adobe\OOBE\PDApp\UWA\UpdaterStartupUtility.exe",
            @"C:\Program Files (x86)\Garmin\Express Tray\ExpressTray.exe",
            @"Chrome\Application\chrome.exe",
            @"Fax\Fax Driver 0.6 Base\hppfaxprintersrv.exe",
            @"C:\Program Files\Autodesk\Autodesk Sync\AdSync.exe",
            @"C:\Program Files\Autodesk\Personal Accelerator for Revit\RevitAccelerator.exe",
            @"C:\Program Files\Common Files\Intel\WirelessCommon\iFrmewrk.exe",
            @"C:\Program Files\DellTPad\Apoint.exe",
            @"C:\Program Files\File Association Helper\FAHConsole.exe",
            @"C:\Program Files\Greenshot\Greenshot.exe",
            @"C:\Program Files\Hewlett-Packard Enterprise\Content Manager\TRIMUserSetup.exe",
            @"C:\Program Files\Hewlett-Packard\HP Records Manager\TRIMUserSetup.exe",
            @"C:\Program Files\IDT\WDM\sttray64.exe",
            @"C:\Program Files\iTunes\iTunesHelper.exe",
            @"C:\Program Files\Kapish\Explorer\KapishTRIMMonitor.exe",
            @"C:\Program Files\Microsoft Office\Office14\BCSSync.exe",
            @"C:\Program Files\Realtek\Audio\HDA\RAVBg64.exe",
            @"C:\Program Files\Realtek\Audio\HDA\RtDCpl64.exe",
            @"C:\Program Files\Realtek\Audio\HDA\RtkNGUI64.exe",
            @"C:\Program Files\Realtek\Audio\HDA\WavesSvc64.exe",
            @"C:\Program Files\VMware\VMware Tools\vmtoolsd.exe",
            @"c:\Program Files\Waves\MaxxAudio\WavesSvc64.exe",
            @"C:\Program Files\Windows Server\Bin\Launchpad.exe",
            @"C:\Users\jb02835\AppData\Local\Blue Jeans\App\BlueJeans.exe",
            @"C:\Users\rw05195\AppData\Local\Programs\Google\Google Photos Backup\Google Photos Backup.exe",
            @"C:\Users\td30437\AppData\Roaming\Smilebox\SmileboxTray.exe",
            @"C:\Windows\system32\hkcmd.exe",
            @"C:\Windows\system32\igfxpers.exe",
            @"C:\Windows\system32\igfxtray.exe",
            @"C:\Windows\system32\RtkUGui64.exe",
            @"C:\Windows\system32\spool\drivers\x64\3\SN0XRCV.exe",
            @"C:\Windows\system32\spool\drivers\x64\3\SS0XRCV.exe",
            @"C:\Windows\WindowsMobile\wmdc.exe",
            @"KapishMonitor.exe",
            @"E:\KapishMonitor.exe",
            @"F:\KapishMonitor.exe",
            @"C:\Program Files (x86)\Intel\Bluetooth\btmshellex.dll",
            @"C:\Windows\SysWOW64\OneDriveSetup.exe",
            @"C:\Users\jb30111\AppData\Local\slack\Update.exe",
            @"C:\Users\jb30111\Downloads\Crycker.exe",
            @"C:\Program Files (x86)\DisplayFusion\DisplayFusion.exe",
            @"C:\Program Files\Docker\Docker\Docker for Windows.exe",
            @"C:\Users\jb30111\AppData\Local\FluxSoftware\Flux\flux.exe",
            @"C:\Users\jb30111\AppData\Local\hain\app-0.6.4\hain.exe",
            @"C:\Program Files\OpenVPN\bin\openvpn-gui.exe",
            @"C:\Program Files (x86)\ScreenshotCaptorPortable\ScreenshotCaptor.exe",
            @"C:\Program Files\Logitech\SetPointP\SetPoint.exe",
            @"C:\Windows\System32\LogiLDA.dll",
            @"C:\WINDOWS\system32\RtkUGui64.exe",
            @"C:\Program Files\Windows Defender\MSASCuiL.exe",
            @"C:\Program Files\Waves\MaxxAudio\WavesSvc64.exe",
            @"Local\Microsoft\OneDrive\OneDrive.exe",
            @"Akamai\netsession_win.exe",
            @"AppData\Local\slack\Update.exe",
            @"bomgar-scc",
            @"Bomgar_Cleanup",
            @"stardock\fences\Fences.exe",
            @"Stardock\Fences\Fences.exe",
            @"Adobe\Reader 11.0\Reader\AdobeCollabSync.exe",
            @"Intel\Intel(R) Rapid Storage Technology\IAStorIcon.exe",
            @"Wondershare\Wondershare Helper Compact\WSHelper.exe",
            @"Local\GoToMeeting\8953\g2mstart.exe",
            @"Realtek\Audio\HDA\RAVCpl64.exe",
            @"Synaptics\SynTP\SynTPEnh.exe",
            @"Getac\Getac Utility\X64Run.exe",
            @"CCleaner\CCleaner64.exe",
            @"Apple\Internet Services\iCloudServices.exe",
            @"SysinternalsSuite\Desktops.exe",
            @"CSR Harmony Wireless Software Stack",
            @"iTunesHelper.exe",
            @"Reader 11.0\Reader\AdobeCollabSync.exe",
            @"airtame-portable\airtame-application.exe",
            @"C:\Windows\system32\StikyNot.exe",
            @"DRG1100Svc.dll",
            @"g2mstart.exe",
            @"Intel\Bluetooth\BleServicesCtrl.exe",
            @"C:\Program Files\Hewlett Packard Enterprise\Content Manager\TRIMUserSetup.exe",
            @"Broadcom\BACS\BacsTray.exe",
        };
    }
}
